save_path: "../tests/parc/april272025/iter_2/testt.yaml"
folder_paths:
- "../tests/parc/april272025/iter_2/p4_phys_record/recorded_motions/"
- "../tests/parc/april272025/iter_1/p4_phys_record/recorded_motions/"
- "../Data/parkour_dataset_april/initial/"
char_filepath: "data/assets/humanoid.xml"
compute_preprocessing_data: true
cut_some_classes_in_half: true
motion_classes_to_cut_in_half:
- "running"
- "platform"
- "vaulting"
- "climbing"
- "mid_climbing"
- "stairs"
- "jumping"
max_terrain_dim_x: 45
max_terrain_dim_y: 45