motions_yaml_path: "../Data/parkour_dataset/v_05_5/jumping/dm/motions.yaml"
num_new_motions: 64
device: "cuda:0"
output_folder_path: "output/_motions/jumping_aug/"
char_model: "data/assets/humanoid.xml"
use_wandb: True
num_iters: 1000
step_size: 0.001
w_root_pos: 1.0
w_root_rot: 10.0
w_joint_rot: 1.0
w_smoothness: 10.0
w_penetration: 100.0
w_contact: 100.0
w_sliding: 1000.0
max_motion_len: 10.0 # s
terrain_aug_type: "NONE"
min_h_scale: 0.8 # 0.8 * 2m = 1.6m
max_h_scale: 1.1
max_heading_angle: 1.0 # degrees
min_heading_angle: 1.0 # degrees
x_scale: [0.95, 1.05]
y_scale: [0.95, 1.05]
terrain_padding_size: 0
slice_terrain: False

char_point_samples:
  sphere_num_subdivisions: 0
  box_num_slices: 2
  box_dim_x: 3
  box_dim_y: 6
  capsule_num_circle_points: 4
  capsule_num_sphere_subdivisions: 0
  capsule_num_cylinder_slices: 4